'use client'
import { createContext, useContext, useState, ReactNode } from 'react'

type Lang = 'tr' | 'en'

const translations = {
  tr: {
    catalog: 'Katalog',
    products: 'Ürünler',
    search: 'Model ara...',
    allSizes: 'Tüm Boyutlar',
    allColors: 'Tüm Renkler',
    size: 'Boyut',
    color: 'Renk',
    modelCode: 'Model Kodu',
    noProducts: 'Ürün bulunamadı',
    home: 'Anasayfa',
    contact: 'İletişim',
    inch: 'İnç',
    whatsapp: 'WhatsApp ile Ulaş',
    filterBy: 'Filtrele',
    silver: 'Gümüş',
    bicolor: 'Siyah & Gümüş',
    black: 'Siyah',
    adminPanel: 'Admin Paneli',
    addProduct: 'Ürün Ekle',
    editProduct: 'Ürün Düzenle',
    deleteProduct: 'Ürün Sil',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    active: 'Aktif',
    passive: 'Pasif',
    uploadImage: 'Görsel Yükle',
    login: 'Giriş Yap',
    logout: 'Çıkış Yap',
    email: 'E-posta',
    password: 'Şifre',
    loading: 'Yükleniyor...',
    productCount: 'ürün',
    heroSubtitle: 'Jant Kapağı Kataloğu 2026',
    productModels: 'Ürün Modeli',
    allRightsReserved: '© 2026 Hanegal. Tüm hakları saklıdır.',
    wheelCover: 'Jant Kapağı',
    otherColors: 'Diğer Renkler',
    clearFilter: 'Temizle',
    whatsappMsg: 'Merhaba, {model} - {size} inc modeli hakkında bilgi almak istiyorum.',
    whatsappGeneral: 'Merhaba, Hanegal jant kapakları hakkında bilgi almak istiyorum.',
    favorites: 'Favorilerim',
    noFavorites: 'Henüz favori eklemediniz.',
    browseCatalog: 'Kataloğa göz at',
    feat1Title: 'Araç Uyumluluğu',
    feat1Desc: 'Hangi araca hangi ürün gerektiğini filtreden saniyeler içinde bulun.',
    feat2Title: 'Geniş Ürün Yelpazesi',
    feat2Desc: '13\'ten 16 inç\'e, gümüş, siyah krom ve bicolor renk seçenekleri.',
    feat3Title: 'Anında WhatsApp Destek',
    feat3Desc: 'Ürün sayfasından tek tıkla WhatsApp\'ta iletişime geçin.',
    footerContact: 'İletişim',
    footerCatalog: 'Katalog',
    footerSlogan: 'Kaliteli jant kapağı, uygun fiyat.',
    whatsappLine: 'WhatsApp',
    settings: 'Ayarlar',
    siteSettings: 'Site Ayarları',
    whatsappNumber: 'WhatsApp Numarası',
    whatsappNumberHint: 'Başında ülke kodu olacak şekilde, sadece rakam (ör. 905436190346)',
    heroTaglineTr: 'Ana Sayfa Alt Yazısı (Türkçe)',
    heroTaglineEn: 'Ana Sayfa Alt Yazısı (İngilizce)',
    footerSloganTr: 'Footer Sloganı (Türkçe)',
    footerSloganEn: 'Footer Sloganı (İngilizce)',
    saveSettings: 'Ayarları Kaydet',
    settingsSaved: 'Ayarlar kaydedildi.',
    adminCredentials: 'Giriş Bilgileri',
    currentEmail: 'Mevcut E-posta',
    newEmail: 'Yeni E-posta (opsiyonel)',
    newPassword: 'Yeni Şifre (opsiyonel)',
    confirmPassword: 'Yeni Şifre (tekrar)',
    updateCredentials: 'Giriş Bilgilerini Güncelle',
    credentialsUpdated: 'Giriş bilgileri güncellendi.',
    passwordsDontMatch: 'Şifreler eşleşmiyor.',
    customerLogin: 'Müşteri Girişi',
    customerSignup: 'Hesap Oluştur',
    signUp: 'Kayıt Ol',
    needAccount: 'Hesabın yok mu? Kayıt ol',
    haveAccount: 'Zaten hesabın var mı? Giriş yap',
    checkEmailToConfirm: 'Hesabını onaylamak için e-postanı kontrol et.',
    myAccount: 'Hesabım',
  },
  en: {
    catalog: 'Catalog',
    products: 'Products',
    search: 'Search model...',
    allSizes: 'All Sizes',
    allColors: 'All Colors',
    size: 'Size',
    color: 'Color',
    modelCode: 'Model Code',
    noProducts: 'No products found',
    home: 'Home',
    contact: 'Contact',
    inch: 'Inch',
    whatsapp: 'Contact via WhatsApp',
    filterBy: 'Filter',
    silver: 'Silver',
    bicolor: 'Black & Silver',
    black: 'Black',
    adminPanel: 'Admin Panel',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    active: 'Active',
    passive: 'Passive',
    uploadImage: 'Upload Image',
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    loading: 'Loading...',
    productCount: 'products',
    heroSubtitle: 'Wheel Cover Catalog 2026',
    productModels: 'Product Models',
    allRightsReserved: '© 2026 Hanegal. All rights reserved.',
    wheelCover: 'Wheel Cover',
    otherColors: 'Other Colors',
    clearFilter: 'Clear',
    whatsappMsg: 'Hello, I would like to get information about the {model} - {size} inch model.',
    whatsappGeneral: 'Hello, I would like to get information about Hanegal wheel covers.',
    favorites: 'My Favorites',
    noFavorites: 'No favorites yet.',
    browseCatalog: 'Browse catalog',
    feat1Title: 'Vehicle Compatibility',
    feat1Desc: 'Find the right product for your car in seconds with our filter.',
    feat2Title: 'Wide Product Range',
    feat2Desc: 'From 13 to 16 inch, in silver, black chrome and bicolor options.',
    feat3Title: 'Instant WhatsApp Support',
    feat3Desc: 'Contact us directly via WhatsApp with one click from any product page.',
    footerContact: 'Contact',
    footerCatalog: 'Catalog',
    footerSlogan: 'Quality wheel covers at the right price.',
    whatsappLine: 'WhatsApp',
    settings: 'Settings',
    siteSettings: 'Site Settings',
    whatsappNumber: 'WhatsApp Number',
    whatsappNumberHint: 'Digits only, with country code (e.g. 905436190346)',
    heroTaglineTr: 'Homepage Tagline (Turkish)',
    heroTaglineEn: 'Homepage Tagline (English)',
    footerSloganTr: 'Footer Slogan (Turkish)',
    footerSloganEn: 'Footer Slogan (English)',
    saveSettings: 'Save Settings',
    settingsSaved: 'Settings saved.',
    adminCredentials: 'Login Credentials',
    currentEmail: 'Current Email',
    newEmail: 'New Email (optional)',
    newPassword: 'New Password (optional)',
    confirmPassword: 'Confirm New Password',
    updateCredentials: 'Update Credentials',
    credentialsUpdated: 'Credentials updated.',
    passwordsDontMatch: 'Passwords do not match.',
    customerLogin: 'Customer Login',
    customerSignup: 'Create Account',
    signUp: 'Sign Up',
    needAccount: "Don't have an account? Sign up",
    haveAccount: 'Already have an account? Log in',
    checkEmailToConfirm: 'Check your email to confirm your account.',
    myAccount: 'My Account',
  },
}

type TranslationKey = keyof typeof translations.tr

interface LangContextType {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
}

const LangContext = createContext<LangContextType | null>(null)

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('tr')
  const t = (key: TranslationKey) => (translations[lang] as Record<string, string>)[key]
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  const ctx = useContext(LangContext)
  if (!ctx) throw new Error('useLang must be used within LangProvider')
  return ctx
}